
ARG NODE_VERSION=22.13.1

FROM node:${NODE_VERSION}-alpine

ARG WORK_DIR=/frontend
ENV PATH ${WORK_DIR}/node_modules/.bin:$PATH

RUN mkdir ${WORK_DIR}
WORKDIR ${WORK_DIR}

COPY package.json ${WORK_DIR}
COPY package-lock.json ${WORK_DIR}

RUN apk add nodejs --no-cache
RUN apk update && apk add tzdata

RUN npm install @angular/cli
RUN npm install

COPY . ${WORK_DIR}

EXPOSE 4200

CMD ng serve --host 0.0.0.0